### PR TITLE
Issue 1 - Create an entry - Chase Simmonds

### PR DESCRIPTION
**Pull request by chase-simmonds**

### CODE REVIEW

**Comment by chase-simmonds** [comment]
Screen Shot 2022-06-01 at 3 39 16 PM

**Comment by chase-simmonds** [comment]
Screen Shot 2022-06-01 at 3 40 05 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Chase, your mobile layout is off as compared to the example, please revise and submit a new screenshot with your revision.

**Comment by chase-simmonds** [comment]
Screen Shot 2022-06-01 at 4 30 36 PM

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
